dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - bin/oologTest
